export const SET_ACTIVE_USER_REQUEST = "SET_ACTIVE_USER_REQUEST"
export const SET_ACTIVE_USER_SUCCESS = "SET_ACTIVE_USER_SUCCESS"
export const SET_ACTIVE_USER_FAILURE = "SET_ACTIVE_USER_FAILURE"

export const REMOVE_ACTIVE_USER = "REMOVE_ACTIVE_USER"