
export const SET_NOTIFICATIONS_REQUEST = "SET_NOTIFICATIONS_REQUEST"
export const SET_NOTIFICATIONS_SUCCESS = "SET_NOTIFICATIONS_SUCCESS"
export const SET_NOTIFICATIONS_FAILURE = "SET_NOTIFICATIONS_FAILURE"

export const NEW_NOTIFICATION_RECEIVED = "NEW_NOTIFICATION_RECEIVED"
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS"
export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ"
export const MARK_ALL_NOTIFICATION_AS_READ = "MARK_ALL_NOTIFICATION_AS_READ"
export const SET_NOTIFICATION_TAB = "SET_NOTIFICATION_TAB";