export const INITIALIZE_CHAT_WINDOW_REQUEST = "INITIALIZE_CHAT_WINDOW_REQUEST"
export const INITIALIZE_CHAT_WINDOW_SUCCESS = "INITIALIZE_CHAT_WINDOW_SUCCESS"
export const INITIALIZE_CHAT_WINDOW_ERROR = "INITIALIZE_CHAT_WINDOW_ERROR"

export const SET_CHAT_ROOM = "SET_CHAT_ROOM"

export const SET_USER_MESSAGES_REQUEST = "SET_USER_MESSAGES_REQUEST"
export const SET_USER_MESSAGES_SUCCESS = "SET_USER_MESSAGES_SUCCESS"
export const SET_USER_MESSAGES_ERROR = "SET_USER_MESSAGES_ERROR"

export const ADD_MESSSAGE_IN_USER_MESSAGES = "ADD_MESSSAGE_IN_USER_MESSAGES"

export const SET_GROUP_MESSAGES_REQUEST = "SET_GROUP_MESSAGES_REQUEST"
export const SET_GROUP_MESSAGES_SUCCESS = "SET_GROUP_MESSAGES_SUCCESS"
export const SET_GROUP_MESSAGES_ERROR = "SET_GROUP_MESSAGES_ERROR"

export const ADD_MESSSAGE_IN_GROUP_MESSAGES = "ADD_MESSSAGE_IN_GROUP_MESSAGES"

export const ADD_NEW_GROUP_IN_GROUPS = "ADD_NEW_GROUP_IN_GROUPS"

export const SET_ONLINE_USERS = "SET_ONLINE_USERS"

export const ADD_CHAT_ID_TO_USER = "ADD_CHAT_ID_TO_USER"