export const SET_CHATROOMS_AND_USERS_IN_CHATWINDOW =
  "SET_CHATROOMS_AND_USERS_IN_CHATWINDOW";

export const SET_ACTIVE_CHAT_ROOM = "SET_ACTIVE_CHAT_ROOM";
export const CLEAR_ACTIVE_CHAT_ROOM = "CLEAR_ACTIVE_CHAT_ROOM";

export const SET_CHAT_MESSAGES_REQUEST = "SET_CHAT_MESSAGES_REQUEST";
export const SET_CHAT_MESSAGES_SUCCESS = "SET_CHAT_MESSAGES_SUCCESS";
export const SET_CHAT_MESSAGES_ERROR = "SET_CHAT_MESSAGES_ERROR";

export const CREATE_NEW_CHAT_ROOM = "CREATE_NEW_CHAT_ROOM";

export const ADD_MESSSAGE_IN_CHAT_MESSAGES = "ADD_MESSSAGE_IN_CHAT_MESSAGES";

export const ADD_NEW_GROUP_IN_GROUPS = "ADD_NEW_GROUP_IN_GROUPS";

export const SET_ONLINE_USERS = "SET_ONLINE_USERS";

export const ADD_NEW_MESSAGE_IN_CHAT = "ADD_NEW_MESSAGE_IN_CHAT";

export const ADD_USER_IN_TYPING_USERS = "ADD_USER_IN_TYPING_USERS";

export const REMOVE_USER_IN_TYPING_USERS = "REMOVE_USER_IN_TYPING_USERS";

export const MARK_CHAT_AS_READ = "MARK_CHAT_AS_READ";

export const UPDATE_LAST_MESSAGE = "UPDATE_LAST_MESSAGE";

export const CLEAR_CHATWINDOW_DATA = "CLEAR_CHATWINDOW_DATA";

export const ADD_USER_IN_CHATROOM = "ADD_USER_IN_CHATROOM";

export const REMOVE_USER_IN_CHATROOM = "REMOVE_USER_IN_CHATROOM";

export const NEW_PRIVATE_ROOM_CREATED = "NEW_PRIVATE_ROOM_CREATED";
