export const INITIALIZE_CHAT_WINDOW_REQUEST = "INITIALIZE_CHAT_WINDOW_REQUEST"
export const INITIALIZE_CHAT_WINDOW_SUCCESS = "INITIALIZE_CHAT_WINDOW_SUCCESS"
export const INITIALIZE_CHAT_WINDOW_ERROR = "INITIALIZE_CHAT_WINDOW_ERROR"

export const SET_CHAT_ROOM = "SET_CHAT_ROOM"

export const SET_USER_MESSAGES_REQUEST = "SET_USER_MESSAGES_REQUEST"
export const SET_USER_MESSAGES_SUCCESS = "SET_USER_MESSAGES_SUCCESS"
export const SET_USER_MESSAGES_ERROR = "SET_USER_MESSAGES_ERROR"

export const ADD_MESSSAGE_IN_USER_MESSAGES = "ADD_MESSSAGE_IN_USER_MESSAGES"