export const ADD_IMAGE_TO_TASK_REQUEST = "ADD_IMAGE_TO_TASK_REQUEST";
export const ADD_IMAGE_TO_TASK_SUCCESS = "ADD_IMAGE_TO_TASK_SUCCESS";
export const ADD_IMAGE_TO_TASK_FAILURE = "ADD_IMAGE_TO_TASK_FAILURE";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE"

export const SET_ACTIVE_TASK_REQUEST = "SET_ACTIVE_TASK_REQUEST"
export const SET_ACTIVE_TASK_SUCCESS = "SET_ACTIVE_TASK_SUCCESS"
export const SET_ACTIVE_TASK_FAILURE = "SET_ACTIVE_TASK_FAILURE"

export const DELETE_ACTIVE_TASK = "DELETE_ACTIVE_TASK"

export const EDIT_TASK = "EDIT_TASK"

export const ADD_SUBTASK = "ADD_SUBTASK"

export const UPDATE_ASSIGNED_USERS_IN_TASK = "UPDATE_ASSIGNED_USERS_IN_TASK"

export const ADD_IMAGE_TO_TASK = "ADD_IMAGE_TO_TASK"

export const ADD_COMMENTS_TO_TASK = "ADD_COMMENTS_TO_TASK"


