export const GET_ALL_DEPARTMENTS_REQUEST = "GET_ALL_DEPARTMENTS_REQUEST"
export const GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS"
export const GET_ALL_DEPARTMENTS_FAILURE = "GET_ALL_DEPARTMENTS_FAILURE"

export const GET_ALL_DESIGNATION_REQUEST = "GET_ALL_DESIGNATION_REQUEST"
export const GET_ALL_DESIGNATION_SUCCESS = "GET_ALL_DESIGNATION_SUCCESS"
export const GET_ALL_DESIGNATION_FAILURE = "GET_ALL_DESIGNATION_FAILURE"

export const SET_DESIGNATION_BY_DEPARTMENT = "SET_DESIGNATION_BY_DEPARTMENT"
