import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MySideDrawer from "@/components/MySideDrawer/MySideDrawer";
import { Box } from "@mui/material";
import CustomThemeProvider from '@/theme/CustomThemeProvider';
import { Toaster } from 'react-hot-toast';
import { AppContextProvider } from '@/context/App/AppContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AppRouterCacheProvider>
           <AppContextProvider>
          <CustomThemeProvider >
          <Toaster position="top-center" />
        <Box className="main_container">{children}</Box>
        </CustomThemeProvider>
        </AppContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
