export const ADD_IMAGE_TO_TASK_REQUEST = "ADD_IMAGE_TO_TASK_REQUEST";
export const ADD_IMAGE_TO_TASK_SUCCESS = "ADD_IMAGE_TO_TASK_SUCCESS";
export const ADD_IMAGE_TO_TASK_FAILURE = "ADD_IMAGE_TO_TASK_FAILURE";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE"

export const SET_ACTIVE_PROJECT_REQUEST = "SET_ACTIVE_PROJECT_REQUEST"
export const SET_ACTIVE_PROJECT_SUCCESS = "SET_ACTIVE_PROJECT_SUCCESS"
export const SET_ACTIVE_PROJECT_FAILURE = "SET_ACTIVE_PROJECT_FAILURE"

export const SET_ACTIVE_TASK_REQUEST = "SET_ACTIVE_TASK_REQUEST"
export const SET_ACTIVE_TASK_SUCCESS = "SET_ACTIVE_TASK_SUCCESS"
export const SET_ACTIVE_TASK_FAILURE = "SET_ACTIVE_TASK_FAILURE"

export const SET_ACTIVE_USER_REQUEST = "SET_ACTIVE_USER_REQUEST"
export const SET_ACTIVE_USER_SUCCESS = "SET_ACTIVE_USER_SUCCESS"
export const SET_ACTIVE_USER_FAILURE = "SET_ACTIVE_USER_FAILURE"

export const SET_PROJECTS_REQUEST = "SET_PROJECTS_REQUEST"
export const SET_PROJECTS_SUCCESS = "SET_PROJECTS_SUCCESS"
export const SET_PROJECTS_FAILURE = "SET_PROJECTS_FAILURE"

export const SET_NOTIFICATIONS_REQUEST = "SET_NOTIFICATIONS_REQUEST"
export const SET_NOTIFICATIONS_SUCCESS = "SET_NOTIFICATIONS_SUCCESS"
export const SET_NOTIFICATIONS_FAILURE = "SET_NOTIFICATIONS_FAILURE"

export const NEW_NOTIFICATION_RECEIVED = "NEW_NOTIFICATION_RECEIVED"
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS"
export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ"
export const MARK_ALL_NOTIFICATION_AS_READ = "MARK_ALL_NOTIFICATION_AS_READ"
export const SET_NOTIFICATION_TAB = "SET_NOTIFICATION_TAB";


