export const SET_ACTIVE_PROJECT_REQUEST = "SET_ACTIVE_PROJECT_REQUEST"
export const SET_ACTIVE_PROJECT_SUCCESS = "SET_ACTIVE_PROJECT_SUCCESS"
export const SET_ACTIVE_PROJECT_FAILURE = "SET_ACTIVE_PROJECT_FAILURE"

export const SET_PROJECTS_REQUEST = "SET_PROJECTS_REQUEST"
export const SET_PROJECTS_SUCCESS = "SET_PROJECTS_SUCCESS"
export const SET_PROJECTS_FAILURE = "SET_PROJECTS_FAILURE"

export const SWITCH_PROJECT = "SWITCH_PROJECT"

export const CREATE_PROJECT = "CREATE_PROJECT"

export const UPDATE_PROJECT_NAME = "UPDATE_PROJECT_NAME"

export const DELETE_ACTIVE_PROJECT = "DELETE_ACTIVE_PROJECT"

export const ADD_COLUMN_TO_SECTION = "ADD_COLUMN_TO_SECTION"

export const ADD_TASK_TO_SECTION = "ADD_TASK_TO_SECTION"

export const CLEAR_SECTION = "CLEAR_SECTION"

export const DELETE_SECTION = "DELETE_SECTION"

export const UPDATE_SECTION_NAME = "UPDATE_SECTION_NAME"

export const Move_SECTION = "Move_SECTION"

export const MOVE_TASK = "SWITCH_PROJECT"

export const EDIT_TASK_IN_PROJECT = "EDIT_TASK_IN_PROJECT"

export const DELETE_TASK_IN_PROJECT = "DELETE_TASK_IN_PROJECT"

export const ADD_IMAGE_TO_TASK_IN_PROJECT = "ADD_IMAGE_TO_TASK_IN_PROJECT"

export const ADD_COMMENTS_TO_TASK_IN_PROJECT = "ADD_COMMENTS_TO_TASK_IN_PROJECT"

export const EDIT_USERS_IN_PROJECT = "EDIT_USERS_IN_PROJECT"



















