const top100Films = [
  {
    label: "The Shawshank Redemption",
    year: 1994,
    imageUrl: "/shaw_shank.jpg",
    description: "A story of hope and friendship.",
  },
  {
    label: "The Godfather",
    year: 1972,
    imageUrl: "/godfather.jpg",
    description: "A tale of power and loyalty.",
  },
  {
    label: "The Dark Knight",
    year: 2008,
    imageUrl: "/dark_night.jpg",
    description: "A superhero masterpiece.",
  },
    { label: 'The Godfather: Part II', year: 1974 },
    { label: '12 Angry Men', year: 1957 },
    { label: "Schindler's List", year: 1993 },
    { label: 'The Lord of the Rings: The Return of the King', year: 2003 },
    { label: 'Pulp Fiction', year: 1994 },
    { label: 'The Good, the Bad and the Ugly', year: 1966 },
    { label: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001 },
    { label: 'Fight Club', year: 1999 },
    { label: 'Forrest Gump', year: 1994 },
    { label: 'Inception', year: 2010 },
    { label: 'The Lord of the Rings: The Two Towers', year: 2002 },
    { label: "One Flew Over the Cuckoo's Nest", year: 1975 },
    { label: 'Goodfellas', year: 1990 },
    { label: 'The Matrix', year: 1999 },
    { label: 'Seven Samurai', year: 1954 },
    { label: 'Star Wars: Episode IV - A New Hope', year: 1977 },
    { label: 'City of God', year: 2002 },
    { label: 'Se7en', year: 1995 },
    { label: 'The Silence of the Lambs', year: 1991 },
    { label: "It's a Wonderful Life", year: 1946 },
    { label: 'Life Is Beautiful', year: 1997 },
    { label: 'The Usual Suspects', year: 1995 },
    { label: 'Léon: The Professional', year: 1994 },
    { label: 'Saving Private Ryan', year: 1998 },
    { label: 'Spirited Away', year: 2001 },
    { label: 'Interstellar', year: 2014 },
    { label: 'Parasite', year: 2019 },
    { label: 'The Green Mile', year: 1999 },
    { label: 'Gladiator', year: 2000 },
    { label: 'The Prestige', year: 2006 },
    { label: 'The Lion King', year: 1994 },
    { label: 'Terminator 2: Judgment Day', year: 1991 },
    { label: 'Back to the Future', year: 1985 },
    { label: 'Whiplash', year: 2014 },
    { label: 'The Departed', year: 2006 },
    { label: 'The Pianist', year: 2002 },
    { label: 'The Dark Knight Rises', year: 2012 },
    { label: 'Joker', year: 2019 },
    { label: 'American History X', year: 1998 },
    { label: 'Inglourious Basterds', year: 2009 },
    { label: 'Coco', year: 2017 },
    { label: 'Toy Story', year: 1995 },
    { label: 'Braveheart', year: 1995 },
    { label: 'Avengers: Endgame', year: 2019 },
    { label: 'The Wolf of Wall Street', year: 2013 },
    { label: 'Amélie', year: 2001 },
    { label: 'The Truman Show', year: 1998 },
    { label: 'Finding Nemo', year: 2003 },
    { label: 'Inside Out', year: 2015 },
    { label: 'The Shining', year: 1980 },
    { label: 'Django Unchained', year: 2012 },
    { label: 'WALL·E', year: 2008 },
    { label: 'Mad Max: Fury Road', year: 2015 },
    { label: 'The Avengers', year: 2012 },
    { label: 'A Beautiful Mind', year: 2001 },
    { label: 'Casino Royale', year: 2006 },
    { label: 'Shutter Island', year: 2010 },
    { label: 'The Grand Budapest Hotel', year: 2014 },
    { label: 'The Great Gatsby', year: 2013 },
    { label: 'Slumdog Millionaire', year: 2008 },
    { label: 'Harry Potter and the Sorcerer\'s Stone', year: 2001 },
    // Add more movies here to make up 100 if needed
  ];
  
  export default top100Films;
  